import { createTheme } from "@fluentui/react";

export const blackTheme = createTheme({
  palette: {
    themePrimary: "#79bdbc",
    themeLighterAlt: "#050808",
    themeLighter: "#131e1e",
    themeLight: "#243938",
    themeTertiary: "#487171",
    themeSecondary: "#6aa6a5",
    themeDarkAlt: "#84c3c2",
    themeDark: "#95cdcc",
    themeDarker: "#aedad9",
    neutralLighterAlt: "#000000",
    neutralLighter: "#000000",
    neutralLight: "#000000",
    neutralQuaternaryAlt: "#000000",
    neutralQuaternary: "#000000",
    neutralTertiaryAlt: "#000000",
    neutralTertiary: "#fafafa",
    neutralSecondary: "#fbfbfb",
    neutralPrimaryAlt: "#fcfcfc",
    neutralPrimary: "#f8f8f8",
    neutralDark: "#fdfdfd",
    black: "#fefefe",
    white: "#000000",
  },
});

export const darkTheme = createTheme({
  isInverted: true,
  palette: {
    themePrimary: "#79bdbc",
    themeLighterAlt: "#f9fcfc",
    themeLighter: "#e6f4f4",
    themeLight: "#d2ebeb",
    themeTertiary: "#a9d7d6",
    themeSecondary: "#86c5c4",
    themeDarkAlt: "#6daaa9",
    themeDark: "#5c8f8f",
    themeDarker: "#446a69",
    neutralLighterAlt: "#302e2d",
    neutralLighter: "#383735",
    neutralLight: "#464443",
    neutralQuaternaryAlt: "#4e4d4b",
    neutralQuaternary: "#555352",
    neutralTertiaryAlt: "#72706e",
    neutralTertiary: "#c8c8c8",
    neutralSecondary: "#d0d0d0",
    neutralPrimaryAlt: "#dadada",
    neutralPrimary: "#ffffff",
    neutralDark: "#f4f4f4",
    black: "#f8f8f8",
    white: "#252423",
  },
});

export const lightTheme = createTheme({
  palette: {
    themePrimary: "#457574",
    themeLighterAlt: "#f5f9f9",
    themeLighter: "#dae9e9",
    themeLight: "#bbd6d5",
    themeTertiary: "#82acac",
    themeSecondary: "#568685",
    themeDarkAlt: "#3e6a69",
    themeDark: "#355959",
    themeDarker: "#274241",
    neutralLighterAlt: "#ecebe9",
    neutralLighter: "#e8e7e6",
    neutralLight: "#dedddc",
    neutralQuaternaryAlt: "#cfcecd",
    neutralQuaternary: "#c6c5c4",
    neutralTertiaryAlt: "#bebdbc",
    neutralTertiary: "#a19f9d",
    neutralSecondary: "#605e5c",
    neutralPrimaryAlt: "#3b3a39",
    neutralPrimary: "#323130",
    neutralDark: "#201f1e",
    black: "#000000",
    white: "#f3f2f1",
  },
});

export const whiteTheme = createTheme({
  palette: {
    themePrimary: "#467877",
    themeLighterAlt: "#f5fafa",
    themeLighter: "#dae9e9",
    themeLight: "#bbd6d6",
    themeTertiary: "#82aead",
    themeSecondary: "#568887",
    themeDarkAlt: "#3f6c6b",
    themeDark: "#355b5a",
    themeDarker: "#274343",
    neutralLighterAlt: "#faf9f8",
    neutralLighter: "#f3f2f1",
    neutralLight: "#edebe9",
    neutralQuaternaryAlt: "#e1dfdd",
    neutralQuaternary: "#d0d0d0",
    neutralTertiaryAlt: "#c8c6c4",
    neutralTertiary: "#a19f9d",
    neutralSecondary: "#605e5c",
    neutralPrimaryAlt: "#3b3a39",
    neutralPrimary: "#323130",
    neutralDark: "#201f1e",
    black: "#000000",
    white: "#ffffff",
  },
});
