import { createTheme } from "@fluentui/react";

export const darkTheme = createTheme({
  palette: {
    themePrimary: "#79bdbc",
    themeLighterAlt: "#f9fcfc",
    themeLighter: "#e6f4f4",
    themeLight: "#d2ebeb",
    themeTertiary: "#a9d7d6",
    themeSecondary: "#86c5c4",
    themeDarkAlt: "#6daaa9",
    themeDark: "#5c8f8f",
    themeDarker: "#446a69",
    neutralLighterAlt: "#302e2d",
    neutralLighter: "#383735",
    neutralLight: "#464443",
    neutralQuaternaryAlt: "#4e4d4b",
    neutralQuaternary: "#555352",
    neutralTertiaryAlt: "#72706e",
    neutralTertiary: "#c8c8c8",
    neutralSecondary: "#d0d0d0",
    neutralPrimaryAlt: "#dadada",
    neutralPrimary: "#ffffff",
    neutralDark: "#f4f4f4",
    black: "#f8f8f8",
    white: "#252423",
  },
});

export const lightTheme = createTheme({
  palette: {
    themePrimary: "#467877",
    themeLighterAlt: "#f5fafa",
    themeLighter: "#dae9e9",
    themeLight: "#bbd6d6",
    themeTertiary: "#82aead",
    themeSecondary: "#568887",
    themeDarkAlt: "#3f6c6b",
    themeDark: "#355b5a",
    themeDarker: "#274343",
    neutralLighterAlt: "#f8f8f8",
    neutralLighter: "#f4f4f4",
    neutralLight: "#eaeaea",
    neutralQuaternaryAlt: "#dadada",
    neutralQuaternary: "#d0d0d0",
    neutralTertiaryAlt: "#c8c8c8",
    neutralTertiary: "#0d0d0c",
    neutralSecondary: "#111110",
    neutralPrimaryAlt: "#151514",
    neutralPrimary: "#252423",
    neutralDark: "#1e1d1c",
    black: "#222120",
    white: "#ffffff",
  },
});
